"""
Constants for Onboarderr

This module defines all application constants, default values, and configuration
keys used throughout the application.
"""

import os

def debug_log(message: str) -> None:
    """Log a debug message only if FLASK_DEBUG is enabled."""
    try:
        flask_debug = os.getenv("FLASK_DEBUG", "0") == "1"
        if flask_debug:
            print(f"[DEBUG] {message}")
    except Exception:
        pass

debug_log("Loading constants module")

# Application constants
APP_NAME = "Onboarderr"
APP_VERSION = "1.0.0"
DEFAULT_PORT = 5000
DEFAULT_HOST = "0.0.0.0"

# Environment file names
ENV_FILE = ".env"
ENV_TEST_FILE = ".env.test"

# Setup and authentication
SETUP_COMPLETE_KEY = "SETUP_COMPLETE"
SITE_PASSWORD_KEY = "SITE_PASSWORD"
ADMIN_PASSWORD_KEY = "ADMIN_PASSWORD"
SECRET_KEY_NAME = "SECRET_KEY"

# Password hashing
SITE_PASSWORD_HASH_KEY = "SITE_PASSWORD_HASH"
SITE_PASSWORD_SALT_KEY = "SITE_PASSWORD_SALT"
ADMIN_PASSWORD_HASH_KEY = "ADMIN_PASSWORD_HASH"
ADMIN_PASSWORD_SALT_KEY = "ADMIN_PASSWORD_SALT"

# Plex configuration
PLEX_TOKEN_KEY = "PLEX_TOKEN"
PLEX_TOKEN_HASH_KEY = "PLEX_TOKEN_HASH"
PLEX_URL_KEY = "PLEX_URL"

# Audiobookshelf configuration
ABS_ENABLED_KEY = "ABS_ENABLED"
AUDIOBOOKSHELF_URL_KEY = "AUDIOBOOKSHELF_URL"
AUDIOBOOKSHELF_TOKEN_KEY = "AUDIOBOOKSHELF_TOKEN"
AUDIOBOOKSHELF_TOKEN_HASH_KEY = "AUDIOBOOKSHELF_TOKEN_HASH"
AUDIOBOOKS_ID_KEY = "AUDIOBOOKS_ID"

# Library configuration
LIBRARY_IDS_KEY = "LIBRARY_IDS"
LIBRARY_NAMES_KEY = "LIBRARY_NAMES"
LIBRARY_CAROUSELS_KEY = "LIBRARY_CAROUSELS"
LIBRARY_CAROUSEL_ORDER_KEY = "LIBRARY_CAROUSEL_ORDER"

# Discord configuration
DISCORD_WEBHOOK_KEY = "DISCORD_WEBHOOK"
DISCORD_USERNAME_KEY = "DISCORD_USERNAME"
DISCORD_AVATAR_KEY = "DISCORD_AVATAR"
DISCORD_COLOR_KEY = "DISCORD_COLOR"
DISCORD_NOTIFY_PLEX_KEY = "DISCORD_NOTIFY_PLEX"
DISCORD_NOTIFY_ABS_KEY = "DISCORD_NOTIFY_ABS"
DISCORD_NOTIFY_RATE_LIMITING_KEY = "DISCORD_NOTIFY_RATE_LIMITING"
DISCORD_NOTIFY_IP_MANAGEMENT_KEY = "DISCORD_NOTIFY_IP_MANAGEMENT"
DISCORD_NOTIFY_LOGIN_ATTEMPTS_KEY = "DISCORD_NOTIFY_LOGIN_ATTEMPTS"
DISCORD_NOTIFY_FORM_RATE_LIMITING_KEY = "DISCORD_NOTIFY_FORM_RATE_LIMITING"
DISCORD_NOTIFY_FIRST_ACCESS_KEY = "DISCORD_NOTIFY_FIRST_ACCESS"

# Service URLs
SERVICE_KEYS = [
    'PLEX', 'LIDARR', 'RADARR', 'SONARR', 'TAUTULLI', 'QBITTORRENT', 'IMMICH',
    'PROWLARR', 'BAZARR', 'PULSARR', 'AUDIOBOOKSHELF', 'OVERSEERR', 'JELLYSEERR'
]

# Quick Access configuration
QUICK_ACCESS_ENABLED_KEY = "QUICK_ACCESS_ENABLED"
QA_PLEX_ENABLED_KEY = "QA_PLEX_ENABLED"
QA_AUDIOBOOKSHELF_ENABLED_KEY = "QA_AUDIOBOOKSHELF_ENABLED"
QA_TAUTULLI_ENABLED_KEY = "QA_TAUTULLI_ENABLED"
QA_OVERSEERR_ENABLED_KEY = "QA_OVERSEERR_ENABLED"
QA_JELLYSEERR_ENABLED_KEY = "QA_JELLYSEERR_ENABLED"

# Rate limiting configuration
RATE_LIMIT_SETTINGS_ENABLED_KEY = "RATE_LIMIT_SETTINGS_ENABLED"
RATE_LIMIT_MAX_LOGIN_ATTEMPTS_KEY = "RATE_LIMIT_MAX_LOGIN_ATTEMPTS"
RATE_LIMIT_MAX_FORM_SUBMISSIONS_KEY = "RATE_LIMIT_MAX_FORM_SUBMISSIONS"
RATE_LIMIT_LOGIN_LOCKOUT_DURATION_KEY = "RATE_LIMIT_LOGIN_LOCKOUT_DURATION"
RATE_LIMIT_IP_SUSPICIOUS_THRESHOLD_KEY = "RATE_LIMIT_IP_SUSPICIOUS_THRESHOLD"
RATE_LIMIT_IP_BAN_THRESHOLD_KEY = "RATE_LIMIT_IP_BAN_THRESHOLD"

# IP Management configuration
IP_MANAGEMENT_ENABLED_KEY = "IP_MANAGEMENT_ENABLED"
IP_WHITELIST_KEY = "IP_WHITELIST"
IP_BLACKLIST_KEY = "IP_BLACKLIST"

# Application settings
SERVER_NAME_KEY = "SERVER_NAME"
ACCENT_COLOR_KEY = "ACCENT_COLOR"
DRIVES_KEY = "DRIVES"
ONBOARDERR_URL_KEY = "ONBOARDERR_URL"
SHOW_SERVICES_KEY = "SHOW_SERVICES"
CUSTOM_SERVICES_URL_KEY = "CUSTOM_SERVICES_URL"
DEFAULT_LIBRARY_KEY = "DEFAULT_LIBRARY"

# Debug and logging
FLASK_DEBUG_KEY = "FLASK_DEBUG"
JS_DEBUG_KEY = "JS_DEBUG"
ENABLE_AUDIT_LOGGING_KEY = "ENABLE_AUDIT_LOGGING"
AUDIT_LOG_RETENTION_DAYS_KEY = "AUDIT_LOG_RETENTION_DAYS"

# Timeouts and intervals
RESTART_DELAY_SECONDS_KEY = "RESTART_DELAY_SECONDS"
POSTER_DOWNLOAD_TIMEOUT_KEY = "POSTER_DOWNLOAD_TIMEOUT"
IMMEDIATE_RESTART_DELAY_KEY = "IMMEDIATE_RESTART_DELAY"
STANDARD_RESTART_DELAY_KEY = "STANDARD_RESTART_DELAY"
LIBRARY_CACHE_TTL_KEY = "LIBRARY_CACHE_TTL"
POSTER_REFRESH_INTERVAL_KEY = "POSTER_REFRESH_INTERVAL"
PLEX_API_TIMEOUT_KEY = "PLEX_API_TIMEOUT"
ABS_API_TIMEOUT_KEY = "ABS_API_TIMEOUT"
DISCORD_API_TIMEOUT_KEY = "DISCORD_API_TIMEOUT"
GENERAL_API_TIMEOUT_KEY = "GENERAL_API_TIMEOUT"

# Default values
DEFAULT_SITE_PASSWORD = "changeme"
DEFAULT_ADMIN_PASSWORD = "changeme2"
DEFAULT_ACCENT_COLOR = "#f4b700"
DEFAULT_SERVER_NAME = "My Server"
DEFAULT_RESTART_DELAY = 15
DEFAULT_POSTER_DOWNLOAD_TIMEOUT = 300
DEFAULT_LIBRARY_CACHE_TTL = 86400
DEFAULT_POSTER_REFRESH_INTERVAL = 86400
DEFAULT_API_TIMEOUT = 10
DEFAULT_DISCORD_API_TIMEOUT = 5

# Rate limiting defaults
DEFAULT_MAX_LOGIN_ATTEMPTS = 5
DEFAULT_MAX_FORM_SUBMISSIONS = 2
DEFAULT_LOGIN_LOCKOUT_DURATION = 3600
DEFAULT_IP_SUSPICIOUS_THRESHOLD = 20
DEFAULT_IP_BAN_THRESHOLD = 50

# File paths
LIBRARY_NOTES_FILE = "library_notes.json"
SECTION7_CONTENT_FILE = "section7_content.json"
POSTERS_DIR = "static/posters"

# HTTP status codes
HTTP_OK = 200
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_INTERNAL_SERVER_ERROR = 500

# Content types
CONTENT_TYPE_JSON = "application/json"
CONTENT_TYPE_HTML = "text/html"

# Session keys
SESSION_USER_KEY = "user"
SESSION_ADMIN_KEY = "admin"
SESSION_LAST_ACTIVITY_KEY = "last_activity"

# Security constants
CSRF_TOKEN_NAME = "csrf_token"
PASSWORD_MIN_LENGTH = 6
SESSION_TIMEOUT = 3600  # 1 hour

# Notification types
NOTIFICATION_TYPE_PLEX = "plex"
NOTIFICATION_TYPE_ABS = "audiobookshelf"
NOTIFICATION_TYPE_RATE_LIMITING = "rate_limiting"
NOTIFICATION_TYPE_IP_MANAGEMENT = "ip_management"
NOTIFICATION_TYPE_LOGIN_ATTEMPTS = "login_attempts"
NOTIFICATION_TYPE_FORM_RATE_LIMITING = "form_rate_limiting"
NOTIFICATION_TYPE_FIRST_ACCESS = "first_access"

# Form field names
FORM_SERVER_NAME = "server_name"
FORM_PLEX_TOKEN = "plex_token"
FORM_PLEX_URL = "plex_url"
FORM_ABS_ENABLED = "abs_enabled"
FORM_AUDIOBOOKS_ID = "audiobooks_id"
FORM_AUDIOBOOKSHELF_URL = "audiobookshelf_url"
FORM_AUDIOBOOKSHELF_TOKEN = "audiobookshelf_token"
FORM_DISCORD_WEBHOOK = "discord_webhook"
FORM_DISCORD_USERNAME = "discord_username"
FORM_DISCORD_AVATAR = "discord_avatar"
FORM_DISCORD_COLOR = "discord_color"
FORM_DISCORD_NOTIFY_PLEX = "discord_notify_plex"
FORM_DISCORD_NOTIFY_ABS = "discord_notify_abs"
FORM_DISCORD_NOTIFY_RATE_LIMITING = "discord_notify_rate_limiting"
FORM_DISCORD_NOTIFY_IP_MANAGEMENT = "discord_notify_ip_management"
FORM_DISCORD_NOTIFY_LOGIN_ATTEMPTS = "discord_notify_login_attempts"
FORM_DISCORD_NOTIFY_FORM_RATE_LIMITING = "discord_notify_form_rate_limiting"
FORM_DISCORD_NOTIFY_FIRST_ACCESS = "discord_notify_first_access"
FORM_ONBOARDERR_URL = "onboarderr_url"
FORM_LIBRARY_IDS = "library_ids"
FORM_ACCENT_COLOR = "accent_color_text"
FORM_SITE_PASSWORD = "site_password"
FORM_ADMIN_PASSWORD = "admin_password"
FORM_DRIVES = "drives"
FORM_LOGO_FILE = "logo_file"
FORM_WORDMARK_FILE = "wordmark_file"

# Debug mode
DEBUG_MODE_KEY = "FLASK_DEBUG" 